channels:
     - conda-forge
dependencies:
     - dlib=19.18.0
     - cmake=3.12.0
     - face_recognition=1.3.0
     - pip
     - pip:
       - streamlit-webcam-example==0.1.0
       - streamlit-webrtc==0.20.1
       - aiortc ==1.0.0
