channels:
     - conda-forge
dependencies:
     - dlib=19.18.0
     - pip:
       - streamlit-webcam-example==0.1.0
       - streamlit==0.84.0
       - face_recognition==1.3.0
       - cmake==3.12.0
