channels:
     - conda-forge
dependencies:
     - numpy
    # - libgcc
   #  - libstdcxx-ng
     - face_recognition
     - dlib
     - streamlit-webcam-example
     - pip
     - pip:
       - streamlit-webcam-example
      # - streamlit
      # - dlib
      # - cmake
