channels:
     - conda-forge
dependencies:
     - dlib
     - numpy
     - libgcc=5.2.0
     - libstdcxx-ng
     - face_recognition
     - pip
     - pip:
       - streamlit-webcam-example
       - streamlit
