channels:
     - conda-forge
dependencies:
     - numpy
    # - libgcc
   #  - libstdcxx-ng
#      - face_recognition
     - dlib
     - pip
     - pip:
          - streamlit-webcam-example
          - face_recognition
      # - streamlit
      # - dlib
      # - cmake
